spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.application.name=Blueprints

spring.datasource.url=jdbc:postgresql://postgres-db:5432/blueprintDB
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.user.password=admin
spring.security.filter.order=10
spring.profiles.active=undersampling
